### ISSUE TITLE
Bower can't find amber-ston

### ISSUE THREAD

**Issue by seandenigris** [JupiterJones/amber-ston#1]
`bower install amber-ston --save`
->
`bower ENOTFOUND     Package amber-ston not found`

**Comment by seandenigris** [comment]
After `git clone`, `bower install ./amber-ston --save` worked

**Comment by JupiterJones** [comment]
Hi Sean,

The project is not ready for use so hasn't been published in Bower yet.

I've just started hacking away at the tests and still have a few issues to resolve before it's safe to include in projects.

I hope to have it in better shape in the next few weeks.

**Comment by seandenigris** [comment]
Ah, okay. Maybe it would be good to mention that in the README. When the instructions failed, I was a bit baffled!

Also, I can't wait until this is ready for use. This is a very good solution to port data from Pharo to Amber. It is more flexible than `#storeOn:` because it maintains internal references and avoids the literal limit :)

One thing I was surprised to see is that the format seems a bit different than Pharo's STON e.g. inst var names are 'likeThis' instead of #likeThis. Is that intentional?

**Comment by JupiterJones** [comment]
It mentions that it's not ready for use right at the top under the title :)

Re: the instVar names - do you mean in serialising Amber objects? There is only a subset of Smalltalk classes in Amber, specifically no Symbols - just Strings.

At the moment, I'm planning on materialising Symbols, but I don't have a solution for determining what should be a Symbol, and what should be a String when serialising. For the specific case of instVars, I'll assume Symbols (since in Pharo and GemStone they, of course, will be) and make a specific serialiser for then... but for everything else, they will end up serialising as Strings, even if they materialised from Symbols.

**Comment by seandenigris** [comment]
True! I should've been more specific - maybe either change the https://github.com/JupiterJones/amber-ston#use-ston-for-amber-as-a-library-in-a-client-project to include the `git clone` and `bower install ./amber-ston --save` :)

Re the instVarNames, since it's totally OT, I'll open another issue and reply there...

**Comment by herby** [comment]
@seandenigris you can install git repo directly as `bower install amber-ston git://github.com/JupiterJones/amber-ston.git --save`. URL gets saved in bower.json, so subsequent `bower install` will work as intended.
